services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    gpus: all
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ${OLLAMA_DATA_PATH}:/root/.ollama
    ports:
      - "11434:11434"
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    restart: always
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"

  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    restart: unless-stopped
    volumes:
      - jupyter-data:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=ollama

  watchtower:
    image: nickfedor/watchtower:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "600"

  dozzle:
    image: amir20/dozzle:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true

  ngrok:
    image: ngrok/ngrok:latest
    pull_policy: always
    restart: unless-stopped
    command:
      - "http"
      - "http://open-webui:8080"
      - "--url"
      - ${NGROK_URL}
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

volumes:
  open-webui:
    external: true
  jupyter-data:
    driver: local
